# Generated by Django 3.1.6 on 2021-02-23 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaApp', '0002_auto_20210219_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyeccion',
            name='pelicula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CinemaApp.peliculas'),
        ),
    ]
