# Generated by Django 3.1.6 on 2021-02-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaApp', '0004_auto_20210227_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='butacas',
            name='estado',
            field=models.IntegerField(choices=[(1, 'libre'), (2, 'reservado')], default=1),
        ),
    ]
