# Generated by Django 3.1.6 on 2021-05-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaApp', '0007_auto_20210307_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='butacas',
            name='estado',
            field=models.IntegerField(choices=[(1, 'libre'), (2, 'reservado'), (3, 'vendida')], default=1),
        ),
    ]
